#!/bin/bash

this_dir=$(pwd)/$(dirname ${BASH_SOURCE[0]})
source ${this_dir}/env.sh
source ${this_dir}/dir.sh

cmd="cd build && ${@}"

docker run --rm -t -i \
       --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
       -v ${BUILD_DIR}:/home/user/build \
       -v ${this_dir}/..:/home/user/project \
       -v ${OUTPUT_DIR}:/tmp \
       ${PROJECT_NAME}/development \
       sh -c "${cmd}"
